### ISSUE TITLE
Performance issue in the difinition of transform_targets_for_output, yolo_tf2/utils/common.py

### ISSUE THREAD

**Issue by DLPerf** [schissmantics/yolo-tf2#32]
Hello, I found a performance issu in the difinition of `transform_targets_for_output`, yolo_tf2/utils/common.py. [tf.range and tf.shape](https://github.com/schissmantics/yolo-tf2/blob/d547efa3bce73c0f5a1423ef7f6b260ebf09267f/yolo_tf2/utils/common.py#L115) will be computed repeatedly, resulting in reduced efficiency. I think they should be created before the outer loop in the `transform_targets_for_output`.

Looking forward to your reply. Btw, I am very glad to create a PR to fix it if you are too busy.

**Comment by schissmantics** [comment]
There are many optimizations that can be made which I'm postponing until I add a test suite in the future. Regarding this optimization, it will only be called once or twice for training, and validation dataset initializations, so the performance gains even if they exist, are negligible.
