### ISSUE TITLE
Training method

### ISSUE THREAD

**Issue by ivs-pychen** [schissmantics/yolo-tf2#33]
I don't know how to create a training instance. Do I need to write a training python file?
Does the dataset need to be tfrecord format? Or, I can train the model from jpg image directly.
What does the "dataset-name" mean?

**Comment by schissmantics** [comment]
You can create a training instance through either A) creating a python file or B) command line, based on your needs. Unless you have a good reason to create a python file and populate it with training code, I recommend using the command line. I already included a training know how [section](https://github.com/schissmantics/yolo-tf2#training) which explains both cases. The dataset can come in a TFRecord or a folder of images + labels, and  the TFRecord will be created. If you're referring to [--dataset-name](https://github.com/schissmantics/yolo-tf2#training-options) flag, it is the name under which the TFRecords will be created.

**Comment by ivs-pychen** [comment]
Thanks for your quick response. I will try it. Thank you!!
