### ISSUE TITLE
Evaluate

### ISSUE THREAD

**Issue by ivs-pychen** [schissmantics/yolo-tf2#36]
How can I evaluate the model on the test dataset instead of valid dataset?
full_dataset_predictions.csv contains info of the full training dataset and it can be divided into train_dataset_predictions.csv and valid_dataset_predictions.csv. Is it right?

**Comment by ivs-pychen** [comment]
```
from yolo_tf2.core.evaluator import Evaluator
import pandas as pd


evaluator = Evaluator(
            input_shape=(416, 416, 3),
            model_configuration='yolo_tf2/config/q_cfg/q-yolov3-voc-pwlq-wa.cfg',
            train_tf_record='data/tfrecords/voc_train.tfrecord',
            valid_tf_record='data/tfrecords/voc_test.tfrecord',
            classes_file='yolo_tf2/config/voc.txt',
            # anchors=anchors,  # defaults to yolov3 anchors
            score_threshold=0.1  # defaults to 0.5 but it's okay to be lower
            )

actual = pd.read_csv('data/tfrecords/full_data.csv')
preds = pd.read_csv('output/data/full_dataset_predictions.csv')

evaluator.calculate_map(
           prediction_data=preds, 
           actual_data=actual, 
           min_overlaps=0.5, 
           display_stats=False)
```
The above is the code for evaluation. But I got the following error.
![image](https://user-images.githubusercontent.com/65347253/133881914-bb783249-5c87-4544-bc49-8b1349e2f1c0.png)

![image](https://user-images.githubusercontent.com/65347253/133881990-ffedd9ff-ebfe-46a0-8ac1-d3e33e66c190.png)
This is the info in full_data.csv
![image](https://user-images.githubusercontent.com/65347253/133882001-d149488c-b7aa-4910-98e1-f5755c8f41d1.png)
This is the info in full_dataset_predictions.csv

**Comment by schissmantics** [comment]
You can use [evaluator.make_predictions](https://github.com/schissmantics/yolo-tf2/blob/master/yolo_tf2/core/evaluator.py#L144) which will produce results for training and validation datasets separately as long as you do not specify `merge=True`, and use the resulting file to calculate mAP.
